!!python/object:configs.WORefinement
checkpoint: ''
exp_name: Ours
extract_method: whole
human_guidance: LLM
library: true
logger_name: WORefinement
loop_feedback: false
record_method: behavior
refine: false
scene_id: 0
task_split: true
