!!python/object:configs.LLMPlusPWOG
checkpoint: ''
exp_name: LLMPlusP
extract_method: None
human_guidance: None
library: false
logger_name: LLMPlusPWOG
loop_feedback: false
record_method: None
refine: false
scene_id: 0
task_split: false
