!!python/object:configs.ActionLibraryWOG
checkpoint: ''
exp_name: Ours
extract_method: rag
human_guidance: None
library: true
logger_name: ActionLibrary
loop_feedback: false
record_method: actions
refine: true
scene_id: 0
task_split: true
