name: leap-agent
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  # Python version
  - python=3.9

  # Core scientific computing (fixed to 1.x for compatibility)
  - numpy>=1.21.0,<2.0
  - scipy>=1.7.0
  - pandas>=1.3.0

  # Machine Learning and NLP
  - pytorch>=1.12.0
  - transformers>=4.20.0
  - sentence-transformers>=2.2.0
  - faiss-cpu>=1.7.0

  # Visualization and plotting
  - matplotlib>=3.5.0
  - seaborn>=0.11.0

  # Data processing
  - pyyaml>=6.0
  - tqdm>=4.64.0

  # Development tools
  - jupyter
  - ipython

  # Computer Vision
  - opencv>=4.5.0

  # System utilities
  - git

  # Install remaining dependencies via pip
  - pip
  - pip:
      # OpenAI and other API clients
      - openai>=1.0.0
      - anthropic>=0.3.0

      # Additional ML/NLP libraries
      - concepts-dm>=0.2.0

      # Logging and utilities
      - colorlog>=6.0.0

      # JSON and data handling
      - jsonlines>=3.0.0

        # Optional: for better performance
      - accelerate>=0.20.0

      # Additional dependencies for Concepts library
      - lark>=1.2.0
      - tabulate>=0.9.0
      - tiktoken>=0.11.0

      # Development and testing
      - pytest>=7.0.0
      - black>=22.0.0
      - flake8>=5.0.0
