!!python/object:configs.CAPWOG
checkpoint: ''
exp_name: CAP
extract_method: None
human_guidance: None
library: false
logger_name: CAPWOG
loop_feedback: false
record_method: None
refine: false
scene_id: 0
task_split: true
