!!python/object:configs.OursWOG
checkpoint: ''
exp_name: Ours
extract_method: whole
human_guidance: None
library: true
logger_name: OursWOG
loop_feedback: false
record_method: behavior
refine: true
scene_id: 0
task_split: true
