!!python/object:configs.PvP
checkpoint: ''
exp_name: CAP
extract_method: whole
human_guidance: LLM
library: true
logger_name: PvP
loop_feedback: false
record_method: behavior
refine: false
scene_id: 0
task_split: true
