!!python/object:configs.WOSplit
checkpoint: ''
exp_name: Ours
extract_method: whole
human_guidance: LLM
library: true
logger_name: WOSplit
loop_feedback: false
record_method: behavior
refine: true
scene_id: 0
task_split: false
