!!python/object:configs.CAPWG
checkpoint: ''
exp_name: CAP
extract_method: None
human_guidance: LLM
library: false
logger_name: CAPWG
loop_feedback: false
record_method: None
refine: false
scene_id: 0
task_split: true
